name: video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.4.15
publish_to: none
environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: https://github.com/amr-kasem/video_player_platform_interface.git
      ref: main 
dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  pigeon: ^22.7.4
  pigeon_generator: ^2.0.6

topics:
  - video
  - video-player
